#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 19 16:16:18 2020

@author: chenshihti
"""

import requests
import json

#header={'user-agent':'自己的agent名稱'}
h={'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36'}
w='https://www.zhihu.com/api/v4/questions/55493026/answers'

r= requests.get(w,headers=h)
data=json.loads(r.text)

#data1為dict 所以不可以for i in list

#1. 取出知乎問題發問時間

print (data['data'][0]['created_time'])
    
#2. 取出第一筆與最後一筆回答的時間

total = len(data['data'])

time_list=[]

for i in range(1,total,1):
    time_list.append(data['data'][i]['created_time'])
    
print (time_list[0]) #取出第一筆
print (time_list[-1]) #最後一筆
    

